"""Generate inert KQL replay from the deployed query body, not a copied filter.

Only the table and clock sources are substituted. All filters, deduplication,
priority selection, limits and projections are the actual source query text.
Generation is offline; executing this datatable query is separate authorization.
"""
from __future__ import annotations
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
FIELDS = [("TimeGenerated", "datetime"), ("EventSubmissionTimestamp", "datetime"),
          ("SyntheticIngestedAt", "datetime"), ("Caller", "string"), ("Claims_d", "dynamic"),
          ("ResourceId", "string"), ("OperationNameValue", "string"), ("ActivityStatusValue", "string"),
          ("EventDataId", "string"), ("CallerIpAddress", "string"), ("ActivitySubstatusValue", "string"),
          ("CorrelationId", "string"), ("OperationId", "string")]


def literal(value, kind):
    if kind == "datetime":
        return "datetime(" + (value if value else "null") + ")"
    if kind == "dynamic":
        return "dynamic(" + json.dumps(value, separators=(",", ":")) + ")"
    if kind == "bool":
        return str(value).lower()
    return json.dumps(value or "")


def build(root=ROOT):
    source = (root / "detections/04-sensitive-operations.kql").read_text(encoding="utf-8")
    header, body = source.split("AzureActivity\n", 1)
    constants = "\n".join(line for line in header.splitlines() if line.startswith("let "))
    actual = "Rows\n" + body.replace("ingestion_time()", "SyntheticIngestedAt").replace("now()", "ReferenceTime")
    actual = re.sub(r"ago\((\d+[dhms])\)", r"(ReferenceTime - \1)", actual)
    fixture = json.loads((root / "fixtures/azureactivity.synthetic.json").read_text(encoding="utf-8"))
    expected = json.loads((root / "fixtures/expected-cases.json").read_text(encoding="utf-8"))
    fields = [("CaseId", "string"), ("ExpectedMatch", "bool"), *FIELDS]
    rows = ["    " + ", ".join(literal(row.get(name), kind) for name, kind in fields) for row in fixture["events"]]
    cases = []
    for row in fixture["events"]:
        case = json.dumps(row["CaseId"])
        cases.append(f"(Evaluate((SyntheticInput | where CaseId == {case})) | summarize ActualPredicate=count() > 0 | extend CaseId={case}, ExpectedMatch={str(row['ExpectedMatch']).lower()})")
    chosen = json.dumps(expected["expected_selected_event_id"])
    cases.append(f'(Evaluate(SyntheticInput) | summarize Returned=count(), Selected=take_any(EventDataId) | extend CaseId="__full_pipeline_selection__", ExpectedMatch=true, ActualPredicate=(Returned == 1 and Selected == {chosen}) | project CaseId, ExpectedMatch, ActualPredicate)')
    return ("// GENERATED by scripts/render_kql_replay.py from the ACTUAL deployed query pipeline.\n"
            "// SYNTHETIC ONLY: table and clock substitutions; no provider ingestion or containment claim.\n"
            + f"let ReferenceTime=datetime({fixture['reference_utc']});\n" + constants + "\n"
            + "let SyntheticInput=datatable(" + ", ".join(name + ":" + kind for name, kind in fields) + ")[\n"
            + ",\n".join(rows) + "\n];\n"
            + "let Evaluate=(Rows:(" + ", ".join(name + ":" + kind for name, kind in FIELDS) + ")) {\n"
            + actual.rstrip() + "\n};\nunion\n" + ",\n".join(cases)
            + "\n| project CaseId, ExpectedMatch, ActualPredicate, MatchesExpectation=(ActualPredicate == ExpectedMatch)\n")


if __name__ == "__main__":
    destination = ROOT / "detections/replay-sensitive-operations.kql"
    destination.write_text(build(), encoding="utf-8")
    print("Generated the actual-query synthetic replay locally; no Kusto or Azure call.")
