"""Generate inert KQL replay from the deployed query body, not a copied filter.

Only the table and clock sources are substituted. All filters, deduplication,
priority selection, limits and projections are the actual source query text.
Generation is offline; executing this datatable query is separate authorization.
"""
from __future__ import annotations
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
FIELDS = [("TimeGenerated", "datetime"), ("EventSubmissionTimestamp", "datetime"),
          ("SyntheticIngestedAt", "datetime"), ("Caller", "string"), ("Claims_d", "dynamic"),
          ("ResourceId", "string"), ("_ResourceId", "string"), ("OperationNameValue", "string"), ("ActivityStatusValue", "string"),
          ("EventDataId", "string"), ("CallerIpAddress", "string"), ("ActivitySubstatusValue", "string"),
          ("CorrelationId", "string"), ("OperationId", "string")]


def literal(value, kind):
    if kind == "datetime":
        return "datetime(" + (value if value else "null") + ")"
    if kind == "dynamic":
        return "dynamic(" + json.dumps(value, separators=(",", ":")) + ")"
    if kind == "bool":
        return str(value).lower()
    return json.dumps(value or "")


def build(root=ROOT):
    source = (root / "detections/04-sensitive-operations.kql").read_text(encoding="utf-8")
    header, body = source.split("AzureActivity\n", 1)
    constants = "\n".join(line for line in header.splitlines() if line.startswith("let "))
    actual = body.replace("ingestion_time()", "SyntheticIngestedAt").replace("now()", "ReferenceTime")
    actual = re.sub(r"ago\((\d+[dhms])\)", r"(ReferenceTime - \1)", actual)
    fixture = json.loads((root / "fixtures/azureactivity.synthetic.json").read_text(encoding="utf-8"))
    expected = json.loads((root / "fixtures/expected-cases.json").read_text(encoding="utf-8"))
    fields = [("CaseId", "string"), ("ExpectedMatch", "bool"), *FIELDS]
    rows = ["    " + ", ".join(literal(row.get(name), kind) for name, kind in fields) for row in fixture["events"]]
    # Azure Monitor rejected Evaluate references both in direct union legs and
    # inside compact view wrappers. Generate each view from the same complete
    # source pipeline instead: no parameterized function lookup is required.
    # The generated repetition must never become a hand-maintained predicate.
    # https://learn.microsoft.com/en-us/kusto/query/union-operator
    # https://learn.microsoft.com/en-us/kusto/query/schema-entities/views
    views = []
    names = []
    for index, row in enumerate(fixture["events"]):
        case = json.dumps(row["CaseId"])
        name = f"ReplayCase{index:03d}"
        names.append(name)
        views.append(f"let {name}=view () {{\nSyntheticInput\n| where CaseId == {case}\n" + actual.rstrip() + f"\n| summarize ActualPredicate=count() > 0\n| extend CaseId={case}, ExpectedMatch={str(row['ExpectedMatch']).lower()}\n}};")
    chosen = json.dumps(expected["expected_selected_event_id"])
    names.append("ReplayFullPipeline")
    views.append('let ReplayFullPipeline=view () {\nSyntheticInput\n' + actual.rstrip() + f'\n| summarize Returned=count(), Selected=take_any(EventDataId)\n| extend CaseId="__full_pipeline_selection__", ExpectedMatch=true, ActualPredicate=(Returned == 1 and Selected == {chosen})\n| project CaseId, ExpectedMatch, ActualPredicate\n}};')
    return ("// GENERATED by scripts/render_kql_replay.py from the ACTUAL deployed query pipeline.\n"
            "// SYNTHETIC ONLY: table and clock substitutions; no provider ingestion or containment claim.\n"
            + f"let ReferenceTime=datetime({fixture['reference_utc']});\n" + constants + "\n"
            + "let SyntheticInput=datatable(" + ", ".join(name + ":" + kind for name, kind in fields) + ")[\n"
            + ",\n".join(rows) + "\n];\n"
            + "\n".join(views) + "\nunion\n" + ",\n".join(names)
            + "\n| project CaseId, ExpectedMatch, ActualPredicate, MatchesExpectation=(ActualPredicate == ExpectedMatch)\n")


if __name__ == "__main__":
    destination = ROOT / "detections/replay-sensitive-operations.kql"
    destination.write_text(build(), encoding="utf-8")
    print("Generated the actual-query synthetic replay locally; no Kusto or Azure call.")
